name: 'Chromatic'
on: push
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: cd ./client/ && yarn

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: ./client/
          token: ${{ secrets.G_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

